// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';


            

            /// Bootstrap configuration for the Kinetic Light Client.
///
/// This module is the single source of truth for how the mobile client
/// discovers the Kinetic network. It mirrors the bootstrap strategy used
/// by `kinetic-daemon/src/config.rs`:
///
///   1. Hardcoded IP multiaddrs — fast, censorship-resistant, always available
///   2. Web2 DNS seed domain lookup — flexible, allows new nodes to be added
///      without shipping an app update
///
/// Both methods are used together so that if the AWS IPs ever change, the
/// DNS seed discovery will find the new nodes automatically.
/// Returns the hardcoded production bootstrap nodes.
/// These are the same multiaddrs as in `kinetic-daemon/src/config.rs`.
Future<List<String>>  productionBootstrapNodes() => RustLib.instance.api.crateApiBootstrapProductionBootstrapNodes();

/// Returns the Web2 DNS seed domains.
/// The network layer resolves these to multiaddrs via DNS TXT records
/// (same as `kinetic-daemon`'s `seed_domains` config field).
Future<List<String>>  seedDomains() => RustLib.instance.api.crateApiBootstrapSeedDomains();

/// Returns all bootstrap nodes — hardcoded IPs plus any discovered via DNS.
/// This is the function used by `daemon.rs` when initializing the light client.
///
/// DNS resolution is handled by the `kinetic-network` event loop itself
/// (it reads `seed_domains` from `NetworkConfig`), so we just return both
/// lists here for config construction.
Future<(List<String>,List<String>)>  allBootstrapNodes() => RustLib.instance.api.crateApiBootstrapAllBootstrapNodes();

            
            