// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'error.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `check_leading_zeros`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

/// Validates that a requested domain name meets the mobile delegation rules.
/// Specifically, the name must be at least 8 characters long.
bool validateDelegationName({required String name}) =>
    RustLib.instance.api.crateApiDelegationValidateDelegationName(name: name);

/// Derives the Ed25519 verifying (public) key bytes from a 32-byte signing (private) key.
/// Used by the HTTP VDF request flow to send the correct pubkey to the desktop node.
Uint8List derivePublicKeyBytesSync({required List<int> privateKeyBytes}) =>
    RustLib.instance.api.crateApiDelegationDerivePublicKeyBytesSync(
      privateKeyBytes: privateKeyBytes,
    );

/// Prepares and encrypts a VDF proof request for a Nostr NIP-04 Direct Message
Future<(VdfJobResponse, String)> prepareVdfRequestNostr({
  required String desktopNpub,
  required String name,
  required List<int> privateKeyBytes,
  required int difficultyBits,
}) => RustLib.instance.api.crateApiDelegationPrepareVdfRequestNostr(
  desktopNpub: desktopNpub,
  name: name,
  privateKeyBytes: privateKeyBytes,
  difficultyBits: difficultyBits,
);

/// Decrypts a VDF proof response received via Nostr NIP-04 Direct Message
Future<Uint8List> decryptVdfProofNostr({
  required String desktopNpub,
  required List<int> privateKeyBytes,
  required String encryptedContent,
}) => RustLib.instance.api.crateApiDelegationDecryptVdfProofNostr(
  desktopNpub: desktopNpub,
  privateKeyBytes: privateKeyBytes,
  encryptedContent: encryptedContent,
);

Future<bool> broadcastMobileReveal({
  required String name,
  required List<int> payload,
  required List<int> privateKeyBytes,
  required List<int> vdfProofBytes,
  required List<int> salt,
  required BigInt drandPulse,
  required String drandRandomness,
}) => RustLib.instance.api.crateApiDelegationBroadcastMobileReveal(
  name: name,
  payload: payload,
  privateKeyBytes: privateKeyBytes,
  vdfProofBytes: vdfProofBytes,
  salt: salt,
  drandPulse: drandPulse,
  drandRandomness: drandRandomness,
);

Future<bool> broadcastMobileHeartbeat({
  required String name,
  required List<int> privateKeyBytes,
}) => RustLib.instance.api.crateApiDelegationBroadcastMobileHeartbeat(
  name: name,
  privateKeyBytes: privateKeyBytes,
);

class VdfJobResponse {
  final String challengeHex;
  final Uint8List salt;
  final BigInt drandPulse;
  final String drandRandomness;
  final BigInt iterations;

  const VdfJobResponse({
    required this.challengeHex,
    required this.salt,
    required this.drandPulse,
    required this.drandRandomness,
    required this.iterations,
  });

  @override
  int get hashCode =>
      challengeHex.hashCode ^
      salt.hashCode ^
      drandPulse.hashCode ^
      drandRandomness.hashCode ^
      iterations.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VdfJobResponse &&
          runtimeType == other.runtimeType &&
          challengeHex == other.challengeHex &&
          salt == other.salt &&
          drandPulse == other.drandPulse &&
          drandRandomness == other.drandRandomness &&
          iterations == other.iterations;
}
