// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'error.freezed.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `fmt`, `fmt`, `fmt`, `fmt`

@freezed
sealed class DaemonError with _$DaemonError implements FrbException {
  const DaemonError._();

  const factory DaemonError.alreadyInitialized() =
      DaemonError_AlreadyInitialized;
  const factory DaemonError.notInitialized() = DaemonError_NotInitialized;
  const factory DaemonError.invalidAppDirectory() =
      DaemonError_InvalidAppDirectory;
  const factory DaemonError.proxyStartFailed(String field0) =
      DaemonError_ProxyStartFailed;
  const factory DaemonError.internal(String field0) = DaemonError_Internal;
}

@freezed
sealed class DelegationError with _$DelegationError implements FrbException {
  const DelegationError._();

  const factory DelegationError.notInitialized() =
      DelegationError_NotInitialized;
  const factory DelegationError.invalidPrivateKey() =
      DelegationError_InvalidPrivateKey;
  const factory DelegationError.invalidName(String field0) =
      DelegationError_InvalidName;
  const factory DelegationError.nameTooShort() = DelegationError_NameTooShort;
  const factory DelegationError.drandFetchFailed() =
      DelegationError_DrandFetchFailed;
  const factory DelegationError.invalidProof(String field0) =
      DelegationError_InvalidProof;
  const factory DelegationError.proofTooLong() = DelegationError_ProofTooLong;
  const factory DelegationError.internal(String field0) =
      DelegationError_Internal;
}

@freezed
sealed class IdentityError with _$IdentityError implements FrbException {
  const IdentityError._();

  const factory IdentityError.notInitialized() = IdentityError_NotInitialized;
  const factory IdentityError.offline() = IdentityError_Offline;
  const factory IdentityError.notFound(String field0) = IdentityError_NotFound;
  const factory IdentityError.internal(String field0) = IdentityError_Internal;
}

@freezed
sealed class ResolverError with _$ResolverError implements FrbException {
  const ResolverError._();

  const factory ResolverError.notInitialized() = ResolverError_NotInitialized;
  const factory ResolverError.offline() = ResolverError_Offline;
  const factory ResolverError.notFound(String field0) = ResolverError_NotFound;
  const factory ResolverError.expired(String field0, BigInt field1) =
      ResolverError_Expired;
  const factory ResolverError.invalidUrl(String field0) =
      ResolverError_InvalidUrl;
  const factory ResolverError.noWebsiteService(String field0) =
      ResolverError_NoWebsiteService;
  const factory ResolverError.internal(String field0) = ResolverError_Internal;
}
