// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

/// Looks up a .kin name in the Kinetic DHT and returns its public identity info.
///
/// This is a read-only operation — it does not create or modify any data.
Future<IdentityInfo> fetchIdentity({required String name}) =>
    RustLib.instance.api.crateApiIdentityFetchIdentity(name: name);

/// Public identity information for a .kin name, shown in the Identity tab.
class IdentityInfo {
  /// The resolved .kin name (e.g. `saif.kin`)
  final String name;

  /// The libp2p PeerId of the node that owns this name
  final String peerId;

  /// Whether the name has an active VDF commitment
  final bool isActive;

  /// Human-readable note about the VDF / expiry status
  final String statusNote;

  const IdentityInfo({
    required this.name,
    required this.peerId,
    required this.isActive,
    required this.statusNote,
  });

  @override
  int get hashCode =>
      name.hashCode ^ peerId.hashCode ^ isActive.hashCode ^ statusNote.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is IdentityInfo &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          peerId == other.peerId &&
          isActive == other.isActive &&
          statusNote == other.statusNote;
}
